releases:
  # Platform
  - name: postgres
    namespace: platform
    chart: oci://registry-1.docker.io/bitnamicharts/postgresql
    values:
      - platform/postgres/values.yaml

  - name: neo4j
    namespace: platform
    chart: neo4j/neo4j
    values:
      - platform/neo4j/values.yaml

  - name: minio
    namespace: platform
    chart: minio/minio
    values:
      - platform/minio/values.yaml

  - name: rabbitmq-operator
    namespace: platform
    chart: ./platform/rabbitmq-operator

  - name: rabbitmq-cluster
    namespace: platform
    chart: ./platform/rabbitmq
    needs:
      - platform/rabbitmq-operator

  # Data Science
  - name: jupyterlab
    namespace: ds
    chart: ./apps/ds/jupyterlab
    needs:
      - platform/minio

  # DATA ENGINEERING
  - name: spark-operator
    namespace: de
    chart: spark-operator/spark-operator
    values:
      - apps/de/spark/values.yaml

  - name: spark-rbac
    namespace: de
    chart: ./apps/de/spark
    needs:
      - de/spark-operator


