releases:
  # Platform
  - name: postgres
    namespace: platform
    chart: oci://registry-1.docker.io/bitnamicharts/postgresql
    values:
      - platform/postgres/values.yaml

  - name: minio
    namespace: platform
    chart: minio/minio
    values:
      - platform/minio/values.yaml

  # Data Science
  - name: jupyterlab
    namespace: ds
    chart: ./apps/ds/jupyterlab
    needs:
      - platform/minio

