extraScrapeConfigs: |
  - job_name: k8s-kube-state-metrics-MyCluster
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
    metric_relabel_configs:
      - target_label: cluster
        replacement: k3s-lab

