service:
  enabled: true
  type: ClusterIP
  port: 3000
  targetPort: 3000


ingress:
  enabled: true
  ingressClassName: nginx
  path: /
  pathType: Prefix

  hosts:
    - ""

  extraPaths:
   - path: /*
     pathType: Prefix
     backend:
       service:
         name: grafana
         port:
           number: 3000
  tls: []

