neo4j:
  name: neo4j-homelab
  resources:
    cpu: "0.5"
    memory: "2Gi"
  password: "changeme123"

image:
  repository: neo4j
  tag: "5.18"
  pullPolicy: IfNotPresent

volumes:
  data:
    mode: "dynamic"
    dynamic:
      storageClassName: "local-path"
