apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-3
  namespace: kafka
spec:
  ports:
  - name: external
    port: 9094
    targetPort: 9094
  - name: internal
    port: 29094
    targetPort: 29094
  selector:
    app: kafka-broker-3
  type: ClusterIP
