apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyterlab-config
  namespace: ds
data:
  jupyter_server_config.py: |
    c.ServerApp.token = ''
    c.ServerApp.password = ''
    c.ServerApp.allow_origin = '*'
    c.ServerApp.ip = '0.0.0.0'
