apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterlab-work
  namespace: ds
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi

