mode: standalone

auth:
  rootUser: admin
  # TODO: added secret
  rootPassword: "changeme123"

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    memory: 4Gi

persistence:
  enabled: true
  existingClaim: "minio-pvc-external"

defaultBuckets: "warehouse,raw-data,processed-data,notebooks"

ingress:
  enabled: false

service:
  type: ClusterIP
  ports:
    api: 9000 # S3 API
    console: 9001    # Web UI

metrics:
  serviceMonitor:
    enabled: false

